In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
from pathlib import Path
import json, glob, shutil, subprocess, os
import requests
import pandas as pd
import numpy as np
from datasets import load_dataset
SAVE_PATH_ADDRESS = '/content/drive/MyDrive/2026-1/NLP/appraisal/nlp-appraisal/data/CovidET-Appraisals/repo'

SAVE_PATH = Path(SAVE_PATH_ADDRESS)

In [15]:
COVIDET_REPO = 'https://github.com/honglizhan/CovidET-Appraisals-Public.git'

subprocess.run(["git", "clone", COVIDET_REPO, str(SAVE_PATH)], check=True)

print("Downloaded repo to:", SAVE_PATH)

Downloaded repo to: /content/drive/MyDrive/2026-1/NLP/appraisal/nlp-appraisal/data/CovidET-Appraisals/repo

In [17]:
all_files = []
for root, dirs, files in os.walk(SAVE_PATH):
    for f in files:
        path = Path(root) / f
        all_files.append(path)

print("Number of files:", len(all_files))
for p in all_files[:100]:
    print(p.relative_to(SAVE_PATH))

Number of files: 96
.gitattributes
README.md
.git/description
.git/config
.git/packed-refs
.git/HEAD
.git/index
.git/hooks/pre-merge-commit.sample
.git/hooks/pre-commit.sample
.git/hooks/pre-push.sample
.git/hooks/pre-applypatch.sample
.git/hooks/pre-rebase.sample
.git/hooks/applypatch-msg.sample
.git/hooks/pre-receive.sample
.git/hooks/fsmonitor-watchman.sample
.git/hooks/update.sample
.git/hooks/push-to-checkout.sample
.git/hooks/commit-msg.sample
.git/hooks/prepare-commit-msg.sample
.git/hooks/post-update.sample
.git/info/exclude
.git/refs/heads/main
.git/refs/remotes/origin/HEAD
.git/objects/pack/pack-49992f360d8ebcac5786279627129e0cf8d48d64.pack
.git/objects/pack/pack-49992f360d8ebcac5786279627129e0cf8d48d64.idx
.git/logs/HEAD
.git/logs/refs/remotes/origin/HEAD
.git/logs/refs/heads/main
Human_EVAL/EVAL_analysis.ipynb
Human_EVAL/EVAL_inter-rator_agreement.ipynb
Human_EVAL/TURKERS-EVAL_data-intersection-ALL_6_models.csv
Human_EVAL/TURKERS-EVAL_data-intersection-TOP_3_models.csv
LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-1.csv
LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-2.csv
LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-3.csv
LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-4.csv
LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-5.csv
LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-1.csv
LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-2.csv
LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-3.csv
LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-4.csv
LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-5.csv
LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-1.csv
LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-2.csv
LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-3.csv
LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-4.csv
LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-5.csv
LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-1.csv
LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-2.csv
LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-3.csv
LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-4.csv
LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-5.csv
LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-1.csv
LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-2.csv
LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-3.csv
LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-4.csv
LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-5.csv
LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-1.csv
LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-2.csv
LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-3.csv
LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-4.csv
LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-5.csv
LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-1.csv
LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-2.csv
LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-3.csv
LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-4.csv
LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-5.csv
LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-1.csv
LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-2.csv
LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-3.csv
LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-4.csv
LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-5.csv
LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-1.csv
LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-2.csv
LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-3.csv
LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-4.csv
LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-5.csv
LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-1.csv
LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-2.csv
LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-3.csv
LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-4.csv
LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-5.csv
LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-1.csv
LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-2.csv
LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-3.csv
LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-4.csv
LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-5.csv
LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-1.csv
LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-2.csv
LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-3.csv
LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-4.csv
LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-5.csv
LLM_responses/prompts/prompt_scale.txt
LLM_responses/prompts/prompts_chatgpt.txt
LLM_responses/prompts/prompts_human.txt
data/CovidET-Appraisals.csv

In [19]:
candidate_files = []
for ext in ["*.csv", "*.tsv", "*.json", "*.jsonl", "*.xlsx", "*.pkl"]:
    candidate_files.extend(SAVE_PATH.rglob(ext))

print("Candidate data files:")
for p in candidate_files:
    print("-", p.relative_to(SAVE_PATH))

Candidate data files:
- Human_EVAL/TURKERS-EVAL_data-intersection-ALL_6_models.csv
- Human_EVAL/TURKERS-EVAL_data-intersection-TOP_3_models.csv
- data/CovidET-Appraisals.csv
- LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-1.csv
- LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-2.csv
- LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-3.csv
- LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-4.csv
- LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-5.csv
- LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-1.csv
- LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-2.csv
- LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-3.csv
- LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-4.csv
- LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-5.csv
- LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-1.csv
- LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-2.csv
- LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-3.csv
- LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-4.csv
- LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-5.csv
- LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-1.csv
- LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-2.csv
- LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-3.csv
- LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-4.csv
- LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-5.csv
- LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-1.csv
- LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-2.csv
- LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-3.csv
- LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-4.csv
- LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-5.csv
- LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-1.csv
- LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-2.csv
- LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-3.csv
- LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-4.csv
- LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-5.csv
- LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-1.csv
- LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-2.csv
- LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-3.csv
- LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-4.csv
- LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-5.csv
- LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-1.csv
- LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-2.csv
- LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-3.csv
- LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-4.csv
- LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-5.csv
- LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-1.csv
- LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-2.csv
- LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-3.csv
- LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-4.csv
- LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-5.csv
- LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-1.csv
- LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-2.csv
- LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-3.csv
- LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-4.csv
- LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-5.csv
- LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-1.csv
- LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-2.csv
- LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-3.csv
- LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-4.csv
- LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-5.csv
- LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-1.csv
- LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-2.csv
- LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-3.csv
- LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-4.csv
- LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-5.csv

In [20]:
def load_any_table(path):
    path = Path(path)
    suffix = path.suffix.lower()
    
    if suffix == ".csv":
        return pd.read_csv(path)
    elif suffix == ".tsv":
        return pd.read_csv(path, sep="\t")
    elif suffix == ".json":
        try:
            return pd.read_json(path)
        except ValueError:
            return pd.read_json(path, lines=True)
    elif suffix == ".jsonl":
        return pd.read_json(path, lines=True)
    elif suffix in [".xlsx", ".xls"]:
        return pd.read_excel(path)
    elif suffix == ".pkl":
        return pd.read_pickle(path)
    else:
        raise ValueError(f"Unsupported file type: {suffix}")

loaded_tables = {}

for p in candidate_files:
    try:
        df = load_any_table(p)
        loaded_tables[str(p)] = df
        print("\n" + "="*80)
        print("FILE:", p.relative_to(SAVE_PATH))
        print("SHAPE:", df.shape)
        print("COLUMNS:")
        print(list(df.columns))
        display(df.head(3))
    except Exception as e:
        print("Could not load:", p, "| Error:", repr(e))

================================================================================
FILE: Human_EVAL/TURKERS-EVAL_data-intersection-ALL_6_models.csv
SHAPE: (372, 13)
COLUMNS:
['HIT ID', 'Assignment ID', 'Worker ID', 'Reddit ID', 'Reddit Post', 'Dim', 'Model', 'Scale', 'Rationale', 'factuality', 'justifies', 'relevance', 'usefulness']

                           HIT ID  ... usefulness
0  36U4VBVNQOCO5B89BDL35JJI3B5RUV  ...         no
1  36U4VBVNQOCO5B89BDL35JJI3B5RUV  ...         no
2  3VP28W7DUNJ8OKXAQ5KH5MKE259FZD  ...      maybe

[3 rows x 13 columns]

================================================================================
FILE: Human_EVAL/TURKERS-EVAL_data-intersection-TOP_3_models.csv
SHAPE: (390, 13)
COLUMNS:
['HIT ID', 'Assignment ID', 'Worker ID', 'Reddit ID', 'Reddit Post', 'Dim', 'Scale', 'Rationale', 'Model', 'factuality', 'justifies', 'relevance', 'usefulness']

                           HIT ID  ... usefulness
0  3QXFBUZ4ZKFXGLZVV2RR6F5B1RVUGH  ...        yes
1  3QXFBUZ4ZKFXGLZVV2RR6F5B1RVUGH  ...        yes
2  3TC2K6WK9G193UKBTK5X8JTLUHZ28R  ...         no

[3 rows x 13 columns]

================================================================================
FILE: data/CovidET-Appraisals.csv
SHAPE: (281, 53)
COLUMNS:
['HIT ID', 'Assignment ID', 'Worker ID', 'Reddit ID', 'Reddit Post', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

                           HIT ID  ...                                    dim24_rationale
0  360ZO6N6KAUVP7FXL2X2G8VG6P9M9W  ...  The narrator did not expect their uncle to die...
1  360ZO6N6KAUVP7FXL2X2G8VG6P9M9W  ...  Though they narrator understands the risk and ...
2  3Z33IC0JD9XEFU96ZUYT34ETXILV9M  ...  The narrator did not seem to expect the situat...

[3 rows x 53 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-1.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     1  ...     0  Tell us why.\n\n#1. I expected the situation t...
1    o77vmk     1  ...     9                                       Tell us why.
2    o78h66     1  ...     0                                       Tell us why.

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-2.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     1  ...     0  I expected the situation to occur.\n\n# Tell u...
1    o77vmk     1  ...     9                                       Tell us why.
2    o78h66     1  ...     0                                       Tell us why.

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-3.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                     dim24_rationale
0    o6lpwn     1  ...     0  I expected the situation to occur.
1    o77vmk     1  ...     1                        Tell us why.
2    o78h66     1  ...     0                        Tell us why.

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-4.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                               dim24_rationale
0    o6lpwn     9  ...     0  I expected the situation to occur.\n\n#12345
1    o77vmk     1  ...     9                                  Tell us why.
2    o78h66     1  ...     0            I expected the situation to occur.

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/alpaca-13B/alpaca-13B_seed-5.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     1  ...     0  Tell us why.\n\n#1. I expected the situation t...
1    o77vmk     1  ...     9                                       Tell us why.
2    o78h66     1  ...     0                                       Tell us why.

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-1.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     5  ...     5  The narrator expected the situation to occur t...
1    o77vmk     5  ...     5  I expected the situation to occur to some exte...
2    o78h66     5  ...     5  The narrator expected the situation to some ex...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-2.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     5  ...     5  The narrator expected the situation to occur t...
1    o77vmk     5  ...     5  I expected the situation to occur to some exte...
2    o78h66     5  ...     5  The narrator expected the situation to occur t...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-3.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     5  ...     5  The narrator expected the situation to occur t...
1    o77vmk     5  ...     5  I expected the situation to occur to some exte...
2    o78h66     5  ...     5  The narrator expected the situation to occur t...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-4.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     5  ...     5  The narrator expected the situation to occur t...
1    o77vmk     5  ...     5  I expected the situation to occur to some exte...
2    o78h66     5  ...     5  The narrator expected the situation to occur t...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/alpaca-7B/alpaca-native_seed-5.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     5  ...     5  The narrator expected the situation to occur t...
1    o77vmk     5  ...     5  I expected the situation to occur to some exte...
2    o78h66     5  ...     5  The narrator expected the situation to occur t...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-1.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn   6.0  ...     1  The narrator expresses shock and disbelief at ...
1    o77vmk   1.0  ...     3  The text doesn't provide enough information to...
2    o78h66   1.0  ...     3  The narrator may have anticipated some negativ...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-2.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn   6.0  ...     1  The narrator expresses shock and disbelief at ...
1    o77vmk   1.0  ...     2  The narrator seems to be expressing frustratio...
2    o78h66   1.0  ...     3  The narrator may have anticipated some negativ...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-3.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     6  ...     1  The narrator expresses shock and disbelief at ...
1    o77vmk     1  ...     3  The text doesn't provide enough information to...
2    o78h66     1  ...     3  The narrator may have anticipated some negativ...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-4.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn   6.0  ...     1  The narrator expresses shock and disbelief at ...
1    o77vmk   1.0  ...     4  The text doesn't explicitly state whether the ...
2    o78h66   1.0  ...     3  The narrator may have anticipated some negativ...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/chatgpt/chatgpt_seed-5.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn   6.0  ...     1  The narrator expresses shock and disbelief at ...
1    o77vmk   1.0  ...     3  The text doesn't provide enough information to...
2    o78h66   1.0  ...     3  The narrator may have anticipated some negativ...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-1.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     0  ...     8  I expected his death to occur about 10 times o...
1    o77vmk     7  ...     7  This is a very difficult question to answer as...
2    o78h66     7  ...     7  I expected the situation to occur to some exte...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-2.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     0  ...     8  I expected his death to occur about 10 times o...
1    o77vmk     7  ...     7  This is a 7 because I expected my company to c...
2    o78h66     7  ...     7  I expected the situation to occur to some exte...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-3.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     0  ...     8  I expected his death to occur about a week lat...
1    o77vmk     7  ...     7  This is a very difficult question to answer as...
2    o78h66     7  ...     7  I expected a notched down mood, but not for th...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-4.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     0  ...     8  I expected his death to occur about a week lat...
1    o77vmk     7  ...     7  I was completely surprised by this revelation....
2    o78h66     7  ...     7  I expected a notched down mood, but not for th...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/dolly-v2-12B/dolly-v2-12B_seed-5.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     0  ...     8  I expected his death to occur about a week lat...
1    o77vmk     7  ...     7  This is a very difficult question to answer as...
2    o78h66     7  ...     7  I expected the situation to occur to some exte...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-1.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     0  ...     2  I dont know how to speak of this grief. I have...
1    o77vmk     7  ...     0  I'm being vague as to not give away my employe...
2    o78h66     7  ...     9  I expected the situation to occur to a certain...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-2.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     7  ...     2  I dont know how to speak of this grief. I have...
1    o77vmk     7  ...     0  I'm being vague as to not give away my employe...
2    o78h66     7  ...     9  I expected the situation to occur to a certain...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-3.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     7  ...     2  I dont know how to speak of this grief. I have...
1    o77vmk     7  ...     0  I'm being vague as to not give away my employe...
2    o78h66     7  ...     9  I expected the situation to occur to a certain...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-4.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     0  ...     2  I dont know how to speak of this grief. I have...
1    o77vmk     7  ...     0  I'm being vague as to not give away my employe...
2    o78h66     7  ...     9  I expected the situation to occur to a certain...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/dolly-v2-7B/dolly-v2-7B_seed-5.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     7  ...     2  I dont know how to speak of this grief. I have...
1    o77vmk     7  ...     0  I'm being vague as to not give away my employe...
2    o78h66     7  ...     9  I expected the situation to occur to a certain...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-1.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     9  ...     5  I expected it to happen, but I didnt expect it...
1    o77vmk     0  ...     5  I'm being vague as to not give away my employe...
2    o78h66     9  ...     5                                                  5

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-2.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     9  ...     5  I expected it to happen, but it didnt happen t...
1    o77vmk     0  ...     5  I'm being vague as to not give away my employe...
2    o78h66     9  ...     5                                                  5

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-3.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     9  ...     5  I expected it to happen, but it didnt happen t...
1    o77vmk     0  ...     5  I'm being vague as to not give away my employe...
2    o78h66     9  ...     5               I'm not surprised by this situation.

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-4.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     9  ...     5  I expected it to happen, but it didnt happen t...
1    o77vmk     0  ...     5  I'm being vague as to not give away my employe...
2    o78h66     9  ...     5  I feel like everything he says is a repeat of ...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Cleaned/flan-t5-xxl/flan-t5-xxl_seed-5.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  dim1  ... dim24                                    dim24_rationale
0    o6lpwn     9  ...     5  I expected it to happen, but it didnt happen t...
1    o77vmk     0  ...     5  I'm being vague as to not give away my employe...
2    o78h66     9  ...     5                                                  5

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-1.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  Tell us why.\n\n#1. I expected the situation t...
1    o77vmk  ...                                   Tell us why.</s>
2    o78h66  ...                                   Tell us why.</s>

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-2.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I expected the situation to occur.\n\n# Tell u...
1    o77vmk  ...                                   Tell us why.</s>
2    o78h66  ...                                   Tell us why.</s>

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-3.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                         dim24_rationale
0    o6lpwn  ...  I expected the situation to occur.</s>
1    o77vmk  ...                        Tell us why.</s>
2    o78h66  ...                        Tell us why.</s>

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-4.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                   dim24_rationale
0    o6lpwn  ...  I expected the situation to occur.\n\n#12345</s>
1    o77vmk  ...                                  Tell us why.</s>
2    o78h66  ...            I expected the situation to occur.</s>

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/alpaca-13B/alpaca-13b_seed-5.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  Tell us why.\n\n#1. I expected the situation t...
1    o77vmk  ...                                   Tell us why.</s>
2    o78h66  ...                                   Tell us why.</s>

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-1.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID   dim1  ...  dim24                                    dim24_rationale
0    o6lpwn  5</s>  ...  5</s>  The narrator expected the situation to occur t...
1    o77vmk  5</s>  ...  5</s>  I expected the situation to occur to some exte...
2    o78h66  5</s>  ...  5</s>  The narrator expected the situation to some ex...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-2.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID   dim1  ...  dim24                                    dim24_rationale
0    o6lpwn  5</s>  ...  5</s>  The narrator expected the situation to occur t...
1    o77vmk  5</s>  ...  5</s>  I expected the situation to occur to some exte...
2    o78h66  5</s>  ...  5</s>  The narrator expected the situation to occur t...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-3.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID   dim1  ...  dim24                                    dim24_rationale
0    o6lpwn  5</s>  ...  5</s>  The narrator expected the situation to occur t...
1    o77vmk  5</s>  ...  5</s>  I expected the situation to occur to some exte...
2    o78h66  5</s>  ...  5</s>  The narrator expected the situation to occur t...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-4.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID   dim1  ...  dim24                                    dim24_rationale
0    o6lpwn  5</s>  ...  5</s>  The narrator expected the situation to occur t...
1    o77vmk  5</s>  ...  5</s>  I expected the situation to occur to some exte...
2    o78h66  5</s>  ...  5</s>  The narrator expected the situation to occur t...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/alpaca-7B/alpaca-native_seed-5.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID   dim1  ...  dim24                                    dim24_rationale
0    o6lpwn  5</s>  ...  5</s>  The narrator expected the situation to occur t...
1    o77vmk  5</s>  ...  5</s>  I expected the situation to occur to some exte...
2    o78h66  5</s>  ...  5</s>  The narrator expected the situation to occur t...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-1.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID dim1  ... dim24                                    dim24_rationale
0    o6lpwn    6  ...     1  The narrator expresses shock and disbelief at ...
1    o77vmk    1  ...     3  The text doesn't provide enough information to...
2    o78h66    1  ...     3  The narrator may have anticipated some negativ...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-2.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID dim1  ... dim24                                    dim24_rationale
0    o6lpwn    6  ...     1  The narrator expresses shock and disbelief at ...
1    o77vmk    1  ...     2  The narrator seems to be expressing frustratio...
2    o78h66    1  ...     3  The narrator may have anticipated some negativ...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-3.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID dim1  ... dim24                                    dim24_rationale
0    o6lpwn    6  ...     1  The narrator expresses shock and disbelief at ...
1    o77vmk    1  ...     3  The text doesn't provide enough information to...
2    o78h66    1  ...     3  The narrator may have anticipated some negativ...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-4.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID dim1  ... dim24                                    dim24_rationale
0    o6lpwn    6  ...     1  The narrator expresses shock and disbelief at ...
1    o77vmk    1  ...     4  The text doesn't explicitly state whether the ...
2    o78h66    1  ...     3  The narrator may have anticipated some negativ...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/chatgpt/chatgpt_seed-5.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID dim1  ... dim24                                    dim24_rationale
0    o6lpwn    6  ...     1  The narrator expresses shock and disbelief at ...
1    o77vmk    1  ...     3  The text doesn't provide enough information to...
2    o78h66    1  ...     3  The narrator may have anticipated some negativ...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-1.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I expected his death to occur about 10 times o...
1    o77vmk  ...  This is a very difficult question to answer as...
2    o78h66  ...  I expected the situation to occur to some exte...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-2.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I expected his death to occur about 10 times o...
1    o77vmk  ...  This is a 7 because I expected my company to c...
2    o78h66  ...  I expected the situation to occur to some exte...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-3.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I expected his death to occur about a week lat...
1    o77vmk  ...  This is a very difficult question to answer as...
2    o78h66  ...  I expected a notched down mood, but not for th...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-4.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I expected his death to occur about a week lat...
1    o77vmk  ...  I was completely surprised by this revelation....
2    o78h66  ...  I expected a notched down mood, but not for th...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/dolly-v2-12B/dolly-v2-12b_seed-5.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I expected his death to occur about a week lat...
1    o77vmk  ...  This is a very difficult question to answer as...
2    o78h66  ...  I expected the situation to occur to some exte...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-1.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I dont know how to speak of this grief. I have...
1    o77vmk  ...  I'm being vague as to not give away my employe...
2    o78h66  ...  I expected the situation to occur to a certain...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-2.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I dont know how to speak of this grief. I have...
1    o77vmk  ...  I'm being vague as to not give away my employe...
2    o78h66  ...  I expected the situation to occur to a certain...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-3.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I dont know how to speak of this grief. I have...
1    o77vmk  ...  I'm being vague as to not give away my employe...
2    o78h66  ...  I expected the situation to occur to a certain...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-4.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I dont know how to speak of this grief. I have...
1    o77vmk  ...  I'm being vague as to not give away my employe...
2    o78h66  ...  I expected the situation to occur to a certain...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/dolly-v2-7B/dolly-v2-7b_seed-5.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I dont know how to speak of this grief. I have...
1    o77vmk  ...  I'm being vague as to not give away my employe...
2    o78h66  ...  I expected the situation to occur to a certain...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-1.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I expected it to happen, but I didnt expect it...
1    o77vmk  ...  I'm being vague as to not give away my employe...
2    o78h66  ...                                              5</s>

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-2.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I expected it to happen, but it didnt happen t...
1    o77vmk  ...  I'm being vague as to not give away my employe...
2    o78h66  ...                                              5</s>

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-3.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I expected it to happen, but it didnt happen t...
1    o77vmk  ...  I'm being vague as to not give away my employe...
2    o78h66  ...           I'm not surprised by this situation.</s>

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-4.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I expected it to happen, but it didnt happen t...
1    o77vmk  ...  I'm being vague as to not give away my employe...
2    o78h66  ...  I feel like everything he says is a repeat of ...

[3 rows x 49 columns]

================================================================================
FILE: LLM_responses/Responses-Raw/flan-t5-xxl/flan-t5-xxl_seed-5.csv
SHAPE: (241, 49)
COLUMNS:
['Reddit ID', 'dim1', 'dim1_rationale', 'dim2', 'dim2_rationale', 'dim3', 'dim3_rationale', 'dim4', 'dim4_rationale', 'dim5', 'dim5_rationale', 'dim6', 'dim6_rationale', 'dim7', 'dim7_rationale', 'dim8', 'dim8_rationale', 'dim9', 'dim9_rationale', 'dim10', 'dim10_rationale', 'dim11', 'dim11_rationale', 'dim12', 'dim12_rationale', 'dim13', 'dim13_rationale', 'dim14', 'dim14_rationale', 'dim15', 'dim15_rationale', 'dim16', 'dim16_rationale', 'dim17', 'dim17_rationale', 'dim18', 'dim18_rationale', 'dim19', 'dim19_rationale', 'dim20', 'dim20_rationale', 'dim21', 'dim21_rationale', 'dim22', 'dim22_rationale', 'dim23', 'dim23_rationale', 'dim24', 'dim24_rationale']

  Reddit ID  ...                                    dim24_rationale
0    o6lpwn  ...  I expected it to happen, but it didnt happen t...
1    o77vmk  ...  I'm being vague as to not give away my employe...
2    o78h66  ...                                              5</s>

[3 rows x 49 columns]

In [22]:
import pandas as pd

covid_df = pd.read_csv(SAVE_PATH / 'data/CovidET-Appraisals.csv')

print("Shape:", covid_df.shape)
print("Unique Reddit posts:", covid_df["Reddit ID"].nunique())
print("Unique annotators:", covid_df["Worker ID"].nunique())
print(covid_df["Worker ID"].value_counts())

rating_cols = [c for c in covid_df.columns if c.startswith("dim") and not c.endswith("_rationale")]
rationale_cols = [c for c in covid_df.columns if c.endswith("_rationale")]

print("Rating columns:", len(rating_cols))
print("Rationale columns:", len(rationale_cols))

all_ratings = pd.concat([covid_df[c] for c in rating_cols])
print("Rating min:", all_ratings.dropna().min())
print("Rating max:", all_ratings.dropna().max())
print("Unique rating values:", sorted(all_ratings.dropna().unique()))
print("Missing ratings:", all_ratings.isna().sum())

Shape: (281, 53)
Unique Reddit posts: 241
Unique annotators: 2
Worker ID
A23ARVB31O6LE3    143
AM6H40LNWSFYA     138
Name: count, dtype: int64
Rating columns: 24
Rationale columns: 24
Rating min: 1.0
Rating max: 9.0
Unique rating values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0)]
Missing ratings: 1052

In [23]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281 entries, 0 to 280
Data columns (total 53 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   HIT ID           281 non-null    object
 1   Assignment ID    281 non-null    object
 2   Worker ID        281 non-null    object
 3   Reddit ID        281 non-null    object
 4   Reddit Post      281 non-null    object
 5   dim1             277 non-null    float64
 6   dim1_rationale   281 non-null    object
 7   dim2             266 non-null    float64
 8   dim2_rationale   281 non-null    object
 9   dim3             273 non-null    float64
 10  dim3_rationale   281 non-null    object
 11  dim4             278 non-null    float64
 12  dim4_rationale   281 non-null    object
 13  dim5             260 non-null    float64
 14  dim5_rationale   281 non-null    object
 15  dim6             271 non-null    float64
 16  dim6_rationale   281 non-null    object
 17  dim7             261 non-null    float64
 18  dim7_rationale   281 non-null    object
 19  dim8             273 non-null    float64
 20  dim8_rationale   281 non-null    object
 21  dim9             260 non-null    float64
 22  dim9_rationale   281 non-null    object
 23  dim10            276 non-null    float64
 24  dim10_rationale  281 non-null    object
 25  dim11            218 non-null    float64
 26  dim11_rationale  281 non-null    object
 27  dim12            272 non-null    float64
 28  dim12_rationale  281 non-null    object
 29  dim13            275 non-null    float64
 30  dim13_rationale  281 non-null    object
 31  dim14            277 non-null    float64
 32  dim14_rationale  281 non-null    object
 33  dim15            268 non-null    float64
 34  dim15_rationale  281 non-null    object
 35  dim16            44 non-null     float64
 36  dim16_rationale  281 non-null    object
 37  dim17            238 non-null    float64
 38  dim17_rationale  281 non-null    object
 39  dim18            69 non-null     float64
 40  dim18_rationale  281 non-null    object
 41  dim19            270 non-null    float64
 42  dim19_rationale  281 non-null    object
 43  dim20            257 non-null    float64
 44  dim20_rationale  281 non-null    object
 45  dim21            249 non-null    float64
 46  dim21_rationale  281 non-null    object
 47  dim22            268 non-null    float64
 48  dim22_rationale  281 non-null    object
 49  dim23            41 non-null     float64
 50  dim23_rationale  281 non-null    object
 51  dim24            251 non-null    float64
 52  dim24_rationale  281 non-null    object
dtypes: float64(24), object(29)
memory usage: 116.5+ KB

In [24]:
covid_df.describe()

             dim1        dim2        dim3  ...       dim22      dim23       dim24
count  277.000000  266.000000  273.000000  ...  268.000000  41.000000  251.000000
mean     2.808664    5.259398    7.249084  ...    7.220149   2.634146    3.338645
std      2.077187    2.780730    1.871872  ...    1.540965   1.996949    2.051551
min      1.000000    1.000000    1.000000  ...    1.000000   1.000000    1.000000
25%      1.000000    2.000000    7.000000  ...    6.000000   1.000000    1.000000
50%      2.000000    6.000000    8.000000  ...    7.000000   2.000000    3.000000
75%      4.000000    7.000000    9.000000  ...    8.000000   4.000000    5.000000
max      9.000000    9.000000    9.000000  ...    9.000000   9.000000    8.000000

[8 rows x 24 columns]

In [25]:
covid_df.head()

                           HIT ID  ...                                    dim24_rationale
0  360ZO6N6KAUVP7FXL2X2G8VG6P9M9W  ...  The narrator did not expect their uncle to die...
1  360ZO6N6KAUVP7FXL2X2G8VG6P9M9W  ...  Though they narrator understands the risk and ...
2  3Z33IC0JD9XEFU96ZUYT34ETXILV9M  ...  The narrator did not seem to expect the situat...
3  3Z33IC0JD9XEFU96ZUYT34ETXILV9M  ...  The narrator did not seem to expect this situa...
4  3XJOUITW9325U1M3B190OHGXAX9TQQ  ...  The narrator describes pre-pandemic mental hea...

[5 rows x 53 columns]